#pragma once
#define IDENFR 0	//标识符
#define INTCON 1	//整形常量   
#define CHARCON 2	//字符常量
#define STRCON 3	//字符串
#define CONSTTK 4	//const
#define INTTK 5		//int
#define CHARTK 6	//char
#define VOIDTK 7	//void
#define MAINTK 8	//main
#define IFTK 9		//if
#define ELSETK 10	//else
#define DOTK 11		//do
#define WHILETK	12	//while	
#define FORTK 13	//for
#define SCANFTK	14	//scanf
#define PRINTFTK 15	//printf
#define RETRUNTK 16	//return 
#define PLUS 17		//+
#define MINU 18		//-
#define MULT 19		//*
#define DIV 20		// /
#define LSS 21		//<
#define LEQ 22		//<=
#define GRE 23		//>	
#define GEQ 24		//>=
#define EQL 25		//==
#define NEQ 26		//!=
#define ASSIGN 27	//=
#define SEMICN 28	//;
#define COMMA 29	//,
#define LPARENT 30	//(
#define RPARENT 31	//)
#define LBRACK 32   //[
#define RBRACK 33	//]
#define LBRACE 34	//{
#define RBRACE 35	//}
